### ISSUE TITLE
Doesn't work with number parameter >100

### ISSUE THREAD

**Issue by waldyrious** [korosuke613/gh-user-stars#8]
If I pass a number parameter larger than 100, the tool doesn't work. All I see is this:

```console
$gh user-stars 101
>
  1/1
> 2021-09-01 00:00:00
```

**Comment by korosuke613** [comment]
@waldyrious 
Thanks for the bug report!

I ran it with the latest commit(b45ced5c52d18619dd5edca9454c89e3f4b974cb) and got the following message.

```
❯ gh user-stars 101
> gh: Requesting 101 records on the `starredRepositories` connection exceeds the `first` limit of 100 records.
```

gh-user-stars is using [User.starredRepositories from GitHub API v4](https://docs.github.com/en/graphql/reference/objects#user
). The `first` argument of this API is a NUMBER. It seems that the maximum value of this `first` is 100.

Therefore, I would explicitly set the maximum NUMBER of gh-user-stars to 100. Specifically, I will try to fix the help and output appropriate error messages.

**Comment by waldyrious** [comment]
Thanks for the quick fix! I can confirm this now warns me appropriately:

```
$ gh user-stars 101
error: the maximum value of NUMBER is 100.
```
